### ISSUE TITLE
What is this for? Eagle?

### ISSUE THREAD

**Issue by docdawning** [xesscorp/RPi_Hat_Template#2]
Howdy, I'm trying to open your schematics in Eagle and it dies with the message:

```
Error:

line 1, column 1: Start tag expected.
```

Is this not an Eagle sch? If not, then what is this intended to be used with?

Thanks a lot for posting this, if I can get it work, it'll save me some time. :)

**Comment by xesscorp** [comment]
No, this is a KiCad project. I haven't done a new design in Eagle in years.

**Comment by docdawning** [comment]
Is KiCad > Eagle for homebrew prototyping?

**Comment by xesscorp** [comment]
That's a complicated argument. Best to go read the many pro/con comparisons of Eagle/KiCad and decide which issues apply to you.

**Comment by docdawning** [comment]
Yeah, fair enough. Thanks for pointing out KiCad exists. Toodles.
