### ISSUE TITLE
RPi_GPIO not found

### ISSUE THREAD

**Issue by ronangaillard** [xesscorp/RPi_Hat_Template#5]
When I delete one of the components in the scheme (J1 or J2) I get the following error :

![image](https://user-images.githubusercontent.com/5607736/51339082-cc303b00-1a8b-11e9-9bfc-af7df1e876c7.png)

Kicad 5.0.1
OSX 10.14.2

**Comment by xesscorp** [comment]
I just opened the project in KiCad 5 and updated the files. Hopefully it will work now.

**Comment by ronangaillard** [comment]
Thanks ! Greatly appreciated :)
